version: "3"

services:
  game-calendar-nestjs:
    container_name: game-calendar-nestjs
    image: game-calendar-nestjs
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      game-calendar:
        ipv4_address: 172.20.0.2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gamecalback.rule=Host(`gamecalback.sb-pro.fr`)"
      - "traefik.http.routers.gamecalback.entrypoints=websecure"
      - "traefik.http.routers.gamecalback.tls.certresolver=myresolver"


# docker network create -d bridge --subnet=172.20.0.0/16 --gateway=172.20.0.1 game-calendar
networks:
  game-calendar:
    external: true
