version: "3"

services:
  game-calendar-nestjs:
    container_name: game-calendar-nestjs
    image: game-calendar-nestjs
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
      # - '/app/node_modules'
