import { ApiProperty } from "@nestjs/swagger";
import { IsNotEmpty, IsString, IsUrl } from "class-validator";

export class AuthorizeUrlDto {
	@ApiProperty({
		description: "Callback URL the provider must redirect the browser back to",
		example: "http://localhost:3002/api/auth/twitch/callback",
	})
	@IsNotEmpty()
	@IsUrl({ require_tld: false })
	redirect_uri: string;

	@ApiProperty({ description: "Opaque CSRF state generated by the caller" })
	@IsNotEmpty()
	@IsString()
	state: string;
}

export class ExchangeDto {
	@ApiProperty({ description: "Authorization code returned by the provider" })
	@IsNotEmpty()
	@IsString()
	code: string;

	@ApiProperty({
		description: "The exact redirect_uri used to obtain the code",
		example: "http://localhost:3002/api/auth/twitch/callback",
	})
	@IsNotEmpty()
	@IsUrl({ require_tld: false })
	redirect_uri: string;
}
